### ISSUE TITLE
v-sliderpanel-navigator blocks components underneath

### ISSUE THREAD

**Issue by inahas** [melistik/vaadin-sliderpanel#6] opened 2015-04-20 16:11 UTC
I have placed a table inside the slider panel (placed on the RIGHT side of the parent container). It works fine but when the slider panel is expanded, The entire right 40px of the slider panel are blocked by v-sliderpanel-navigator div which prevents the user from clicking on the scroll bar or anything in that area.

**Comment by inahas** [comment] 2015-04-20 18:28
Adding this to my theme works around the problem. I guess this may be problematic if I have drop downs to other floating items on the far right of the panel, but in my case I don't so this a fine workaround for me.

```
.v-sliderpanel-navigator {
    z-index: 0;
}
```

**Comment by melistik** [comment] 2015-04-20 20:11
Hi,

thanks for your question and your own answer ;)
Could you please post the code to your problem example?
I will try to fix this CSS-Issue...

Best regards

**Comment by melistik** [comment] 2015-04-25 07:58
Hi could you please post your example or i will close this issue?!

**Comment by inahas** [comment] 2015-04-26 02:22
Hi. I tried to reproduce the issue with a sample code but I was unable to. 

Here is the a screenshot of the slider when used in our production application. Notice that the v-slider-panel-navigator has no position attribute and is located at the far right edge of the screen which causes it to overlap the underlying scroll bar (if the z-index is left at 9991).

![screen shot 2015-04-25 at 9 02 48 pm](https://cloud.githubusercontent.com/assets/7094874/7335571/8217ebfa-eb8f-11e4-92c7-e1ec28051f29.png)

However, when I tried to reproduce the issue, I got a different behavior. Here's a screenshot. Notice that the v-slider-panel-navigator has a fixed left position argument of -300px which makes it shift properly to the left of the slider.

![screen shot 2015-04-25 at 9 05 35 pm](https://cloud.githubusercontent.com/assets/7094874/7335583/0783f7fc-eb90-11e4-983c-b87f38b1e534.png)

There must be something in my container layout CSS that is overriding the left position setting. My component hierarchy is quite complex and the slider panel so it is difficult to tell which parent CSS maybe affecting the positioning. But if there is something I can add to help locate the conflict let me know and I will investigate and reply.

**Comment by melistik** [comment] 2015-04-26 19:24
mhh one time the navigator itself has a style with left -300px and the other time it's child tab has a style right 410px. Do you use in both applications the same version of the SliderPanel?

I've change a bit the behavior from version to version. The red example uses an old version - it seems so because in the current code I don't change the style of the tab!

**Comment by inahas** [comment] 2015-04-27 05:49
I am using Vaadin 7.4.4 and SliderPanel 1.0.4 in both cases.

**Comment by melistik** [comment] 2015-04-27 06:34
Hi could you please upgraded at least to [1.0.5](https://github.com/melistik/vaadin-sliderpanel/releases/tag/vaadin-sliderpanel-root-1.0.5) I've fixed some of your mentioned issues...

**Comment by inahas** [comment] 2015-04-27 15:41
I updated to 1.0.6 and now the v-sliderpanel-navigator shifts properly. However, that div now blocks whatever underneath it (eg. a drop down in screenshot below) even with z-index = 0 :(

![untitled](https://cloud.githubusercontent.com/assets/7094874/7351251/bfae325e-ecc9-11e4-8ae2-87c4848a9640.png)

**Comment by inahas** [comment] 2015-04-27 15:55
You can actually reproduce the issue with the online demo. Just resize the window to force the slider tab to overlap the buttons as in this screenshot:

![untitled](https://cloud.githubusercontent.com/assets/7094874/7351614/d6693ba4-eccb-11e4-8f35-8fcc3db7a45a.png)

**Comment by melistik** [comment] 2015-04-27 17:48
Hi inahas,
yeah this block is kown on my site. The problem is, when I remove the navigator div then a flexibel position of the tab (beginning, middle and end) is not possible because it will get positioned relative to it. Maybe I will try to finde a workaround for the next release but currently I would say you need to live with it ;) sorry...

**Comment by inahas** [comment] 2015-04-27 17:58
Thanks. 

I will probably go back to 1.0.4 since my z-index workaround worked well, Hopefully, you'll figure out a real fix soon though.

**Comment by melistik** [comment] 2015-04-28 16:24
Hi inahas,

I've found an easy solution. that works on my test with version 1.0.6. 
You only need to add one property to the css of .v-sliderpanel-navigator and .v-sliderpanel-tab

``` css
.v-sliderpanel-navigator {
   pointer-events: none;
}
.v-sliderpanel-tab {
   pointer-events: all;
}
```

This will give the browser a hint what should be clickable.

Please try it out and give me feedback - afterwards I will do a release...

**Comment by inahas** [comment] 2015-04-28 22:22
Works perfectly! Thanks.

**Closed as completed** 2015-04-29 06:38 UTC
Labels: question
